--- 

- hosts: all
  become: true
  tasks:

  - name: copy file
    copy:
      src: [identified server]
      dest: [files]
      owner: wknight7
      group: wknight7
      mode: 0644

- hosts: workstations         # note this is workstation.... so we can provision our own computers
  become: true
  tasks: 

  - name: install unzip     ## allows you to unzip file from the source 
    package:
      name: unzip

  - name: install terraform   #  
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin   # common directory where binaries are stored
      remote_src: yes
      mode: 0755
      owner: wknight7
      group: wknight7




# this is from Learn Limux TV - ansible Series - video 11 
# https://www.youtube.com/watch?v=teEhLgHpGgo


# add user 

- hosts: all
  become: true
  tasks:

  - name: create simone user
    tags: always
    user:
      name: simone
      groups: root,adm

  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBoZNFWr6XqPvSTTfTw5QPLwjHwoQgfqLUBRgweuP3Gf ansible"

  - name: add sudoers file for simone
    tags: always
    copy: 
      src: sudoer_simone
      dest: /etc/sudoers.d/simone
      owner: root
      group: root
