---

- hosts: all
  become: true
  tasks:

  - name: update systems
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: upgrade systems
    apt:
      upgrade: dist
    when: ansible_distribution in ["Debian", "Ubuntu"]
